### ISSUE TITLE
I don't want to use CocoaPods

### ISSUE THREAD

**Issue by mahdidavoodi7** [cedarstudios/cedarmaps-react-native-sdk#7]
Do you have another way to install this doc for IOS ?

Thanks

**Comment by ghost** [comment]
Since our SDK is based on Mapbox and Mapbox is using CocoaPods for its dependencies, we don't officially support what you are asking for.
There is a way for not using CocoaPods thought. You could create a new project with CocoaPods integrated. Download all needed dependencies for your main project over there and move them from Pods folder to anywhere in your app. You should be aware of relative addresses though.
